adguardhome_admin_password: ENC[AES256_GCM,data:REDACTED]
financial_dashboard_db_password: ENC[AES256_GCM,data:REDACTED]
gitea_db_password: ENC[AES256_GCM,data:REDACTED]
immich_db_password: ENC[AES256_GCM,data:REDACTED]
nextcloud_db_password: ENC[AES256_GCM,data:REDACTED]
nextcloud_mysql_root_password: ENC[AES256_GCM,data:REDACTED]
npm_db_password: ENC[AES256_GCM,data:REDACTED]
npm_mysql_root_password: ENC[AES256_GCM,data:REDACTED]
paperless_db_password: ENC[AES256_GCM,data:REDACTED]
paperless_secret_key: ENC[AES256_GCM,data:REDACTED]
vaultwarden_admin_token: ENC[AES256_GCM,data:REDACTED]
grafana_admin_password: ENC[AES256_GCM,data:REDACTED]
paperless_admin_user: ENC[AES256_GCM,data:REDACTED]
paperless_admin_password: ENC[AES256_GCM,data:REDACTED]
media_stack_wireguard_private_key: ENC[AES256_GCM,data:REDACTED]
cloudflare_api_token: ENC[AES256_GCM,data:REDACTED]
pocketid_encryption_key: ENC[AES256_GCM,data:REDACTED]
restic_password: ENC[AES256_GCM,data:REDACTED]
restic_aws_access_key_id: ENC[AES256_GCM,data:REDACTED]
restic_aws_secret_access_key: ENC[AES256_GCM,data:REDACTED]
restic_s3_repo: ENC[AES256_GCM,data:REDACTED]
media_stack_wireguard_addresses: ENC[AES256_GCM,data:REDACTED]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uwwvt34sn5krnvmy8t9zrskvhzvmys6w2w5verwvxqfqcm3t8pxqta6vws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBK3B4SE4rTjVvVHRtZVVj
            N3dHWkVmMVJwcXlsNm5Gc3ZtREw1dEpSZHlZCm5Pd2RHb0Zydk1FL3VNaVNLZTQ2
            MkNyeFYrajFwR2hNQmNGU0RWaERqRWsKLS0tIGlab0xSN1FXS3FxYnRFcENEcDlx
            c01RTGNPYkVnQzBXc0xpNFdyZW14TGsKGkSAHBfdTVer1YVX8h0C9dtBC2QYpGL0
            vqVLzKztsWcIAktBAz/ee5DoByb76KNvmlblzkFt9hY7dX8t+9NvJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-17T20:55:19Z"
    mac: ENC[AES256_GCM,data:REDACTED]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
