apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden-ingress
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`vault.example.com`)
    services:
    - name: vaultwarden
      port: 80
  tls:
    certResolver: cloudflare
