---
- name: Configure UFW firewall
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "22"
    - "80"
    - "443"
    - "6443"
  when: ansible_os_family == "Debian"

- name: Enable UFW firewall with default deny
  community.general.ufw:
    state: enabled
    default: deny
  when: ansible_os_family == "Debian"
