apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
  namespace: default
  labels:
    app: media-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
