apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: uptime-kuma-ingress
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`uptime.example.com`)
    services:
    - name: uptime-kuma
      port: 3001
  tls:
    certResolver: cloudflare
